version: '3.2'
services:

  node1:
    build:
      context: node
      args:
        GRADLE_VERSION: "4.10.3"
        CORE_VERSION: "0.9.2"
        CORE_BRANCH: "master"
        CLI_VERSION: "0.9.2"
        CLI_BRANCH: "de2e3397ca1e30e5f72fa136b8cae8ae55b10508"
        CONF_TIMESTAMP: "2019-05-18T09:05:00Z"
        CONF_HOST_IP: 0.0.0.0:9090
        CONF_PRIV_KEY: "7a93d447bffe6d89e690f529a3a0bdff8ff6169172458e04849ef1d4eafd7f86"
        CONF_PEER_1: 0.0.0.0:9091
        CONF_PEER_2: 0.0.0.0:9092
        CONF_NAME: Node-1
    image: node-1
    container_name: node-1
    ports:
      - "9090:9090"

  node2:
    build:
      context: node
      args:
        GRADLE_VERSION: "4.10.3"
        CORE_VERSION: "0.9.2"
        CORE_BRANCH: "master"
        CLI_VERSION: "0.9.2"
        CLI_BRANCH: "de2e3397ca1e30e5f72fa136b8cae8ae55b10508"
        CONF_TIMESTAMP: "2019-05-18T09:05:00Z"
        CONF_HOST_IP: 0.0.0.0:9091
        CONF_PRIV_KEY: "7a93d447bffe6d89e690f529a3a0bdff8ff6169172458e04849ef1d4eafd7f86"
        CONF_PEER_1: 0.0.0.0:9090
        CONF_PEER_2: 0.0.0.0:9092
        CONF_NAME: Node-2
    image: node-2
    container_name: node-2
    ports:
      - "9091:9091"

  node3:
    build:
      context: node
      args:
        GRADLE_VERSION: "4.10.3"
        CORE_VERSION: "0.9.2"
        CORE_BRANCH: "master"
        CLI_VERSION: "0.9.2"
        CLI_BRANCH: "de2e3397ca1e30e5f72fa136b8cae8ae55b10508"
        CONF_TIMESTAMP: "2019-05-18T09:05:00Z"
        CONF_HOST_IP: 0.0.0.0:9092
        CONF_PRIV_KEY: "7a93d447bffe6d89e690f529a3a0bdff8ff6169172458e04849ef1d4eafd7f86"
        CONF_PEER_1: 0.0.0.0:9090
        CONF_PEER_2: 0.0.0.0:9091
        CONF_NAME: "Node-3"
    image: node-3
    container_name: node-3
    ports:
      - "9092:9092"